name: Download python-telegram-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions: 
  contents: write  # Grant write permissions for pushing changes

jobs:
  download_packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the desired Python version

    - name: Clear the files directory using Git
      run: |
        git rm -r --ignore-unmatch files/*  # Remove the tracked files (ignore if no files)
        rm -rf files/*                      # Remove the files from the local filesystem

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir -p files/  # Ensure the directory exists
        pip download python-telegram-bot -d files/

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add files/
        git commit -m "Download python-telegram-bot to files/"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
