name: Build OpenWrt Package2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/22.03.0/targets/x86/64/openwrt-sdk-22.03.0-x86-64.tar.xz
          tar -xf openwrt-sdk-22.03.0-x86-64.tar.xz
          mv openwrt-sdk-22.03.0-x86-64 openwrt-sdk
          cd openwrt-sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Set up environment
        run: |
          cd openwrt-sdk
          make defconfig

      - name: Build python-telegram-bot package
        run: |
          cd openwrt-sdk
          mkdir -p package/python-telegram-bot
          cp -r ../package/python-telegram-bot/* package/python-telegram-bot/
          make package/python-telegram-bot/compile V=s
          
      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: python-telegram-bot
          path: openwrt-sdk/bin/packages/x86_64/
